#pragma once
#include "SourceFile.h"


EXTERNC_BEG

enum {
    MYC_TOK_KWAUTO = INT32_MIN,
	MYC_TOK_KWBREAK,
	MYC_TOK_KWCASE,
	MYC_TOK_KWCHAR,
	MYC_TOK_KWCONST,
	MYC_TOK_KWCONTINUE,
	MYC_TOK_KWDEFAULT,
	MYC_TOK_KWDO,
	MYC_TOK_KWDOUBLE,
	MYC_TOK_KWELSE,
	MYC_TOK_KWENUM,
	MYC_TOK_KWEXTERN,
	MYC_TOK_KWFLOAT,
	MYC_TOK_KWFOR,
	MYC_TOK_KWGOTO,
	MYC_TOK_KWIF,
	MYC_TOK_KWINLINE,
	MYC_TOK_KWINT,
	MYC_TOK_KWLONG,
	MYC_TOK_KWREGISTER,
	MYC_TOK_KWRESTRICT,
	MYC_TOK_KWRETURN,
	MYC_TOK_KWSHORT,
	MYC_TOK_KWSIGNED,
	MYC_TOK_KWSIZEOF,
	MYC_TOK_KWSTATIC,
	MYC_TOK_KWSTRUCT,
	MYC_TOK_KWSWITCH,
	MYC_TOK_KWTYPEDEF,
	MYC_TOK_KWUNION,
	MYC_TOK_KWUNSIGNED,
	MYC_TOK_KWVOID,
	MYC_TOK_KWVOLATILE,
	MYC_TOK_KWWHILE,
	MYC_TOK_KW_ALIGNAS,
	MYC_TOK_KW_ALIGNOF,
	MYC_TOK_KW_ATOMIC,
	MYC_TOK_KW_BOOL,
	MYC_TOK_KW_COMPLEX,
	MYC_TOK_KW_GENERIC,
	MYC_TOK_KW_IMAGINARY,
	MYC_TOK_KW_NORETURN,
	MYC_TOK_KW_STATIC_ASSERT,
	MYC_TOK_KW_THREAD_LOCAL,
	MYC_TOK_KW__ASM__,
	MYC_TOK_KW__ATTRIBUTE__,
	MYC_TOK_KW__TYPEOF__,

	MYC_TOK_ARROW,
	MYC_TOK_INC,
	MYC_TOK_DEC,
	MYC_TOK_SHL,
	MYC_TOK_SHR,
	MYC_TOK_LEQ,
	MYC_TOK_GEQ,
	MYC_TOK_EQL,
	MYC_TOK_NEQ,
	MYC_TOK_LAND,
	MYC_TOK_LOR,
	MYC_TOK_COLONCOLON,
	MYC_TOK_ELLIPSIS,
	MYC_TOK_MULASSIGN,
	MYC_TOK_DIVASSIGN,
	MYC_TOK_MODASSIGN,
	MYC_TOK_ADDASSIGN,
	MYC_TOK_SUBASSIGN,
	MYC_TOK_SHLASSIGN,
	MYC_TOK_SHRASSIGN,
	MYC_TOK_BANDASSIGN,
	MYC_TOK_XORASSIGN,
	MYC_TOK_BORASSIGN,
	MYC_TOK_HASHHASH,

    MYC_TOK_LITINT,
    MYC_TOK_LITFLOAT,
    MYC_TOK_LITCHAR,
    MYC_TOK_LITSTRING,

    MYC_TOK_IDENTIFIER,
    MYC_TOK_EOF = -1
};
typedef int32_t MycTokenId;


typedef struct MycToken {
    MycTokenId id;
    MycSourcePosition beg;
    MycSourcePosition end;

    union {
        uint64_t intlit;
        double floatlit;
        char charlit;
		String str;
    };
} MycToken;

EXTERNC_END
